### ISSUE TITLE
Add image to recipe and send to flask

### ISSUE THREAD

**Issue by Tomberino** [jod35/Flask-React-Recipes#1]
Hi, 

thanks for this great tutorial. I watched all videos. Very helpful content.

Could you please show how to send an image file from createRecipe.js to flask to save to database? I think that json.stringify(data) does not work for this.

Thank you very much.

Tom

**Comment by jod35** [comment]
Hey,
I am glad my video helped. I would like to start by advising that saving files to your database will really have some performance issues with your backend (API). Why not use a third-party service like Cloudinary or firebase cloud storage and then go ahead and store the download URL of the image in your database.
