### ISSUE TITLE
recipes not deleted from list of recipes when new user signs in

### ISSUE THREAD

**Issue by 3awny** [jod35/Flask-React-Recipes#2]
Do you know how this can be updated?

Thank you in advance.

**Comment by jod35** [comment]
Greetings, I would like to understand your question in detail.

**Comment by 3awny** [comment]
when I create a recipe with a specific user. Then I sign out and sign up a new user. This new user has the recipes of the previous user still visible in the list of recipes

**Comment by jod35** [comment]
I now understand the problem. Please change the list of recipes you render on the home page to be those of a specific user.

```
recipes=Recipe.query.filter_by(user='blablabla')
```

Hope that helps.

**Comment by 3awny** [comment]
true although its not that simple. It also required some changes in the model i.e. to include user field in recipe model as many-to-one relationship with User model.
Also in the get function of the get all recipes, `@jwt_required()` is needed to get the current user using `get_jwt_identity()`. Also on client side its required to pass in auth header in home.js. 
But with all this done im getting error

`flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header`

**Comment by 3awny** [comment]
is there a specific way to pass in requestOptions to GET fetch statement on client side
